baseURL = "https://polite-dune-093dc2900.3.azurestaticapps.net"
DefaultContentLanguage = "en"
title = "All about Neil Alfred Salazar"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

tag = ["About", "hobby", "Image"]

[Params]
#  homeTitle = "Beautiful Hugo Theme"
  subtitle = "Simple Information About Myself"
  logo = "img/NIcon.png"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  facebook = "https://www.facebook.com/neilalfred.salazar.3"
  twitter = "https://twitter.com/neilalfred08"
  linkedin = "https://www.linkedin.com/in/neil-alfred-salazar-50ba63268/"
  instagram = "https://www.instagram.com/neilalfredsalazar/" 

[[menu.main]]
    parent = "hobby"
    name = "My Hobbies"
    url = "posts/hobby"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "Projects"
    url = "posts/image"
    weight = 1

